packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@parcel/watcher': false
  '@scarf/scarf': false
  bun: false
  esbuild: false
  inotify: false
  pnpm: true
linkWorkspacePackages: true
minimumReleaseAgeExclude:
  - svgo@4.1.0
overrides:
  svgo@>=4.0.0 <4.1.0: ^4.1.0
