name: Upload Coverage to Coveralls

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Test on ubuntu-latest with Node.js 22
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Test with coverage
        run: pnpm run test:cov

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: false
